

---
spring:
  profiles: dev
  session:
    store-type: redis
    timeout: 2000000
  datasource:
      firstdb:
        jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/XE?allowMultiQueries=true
        username: ENC(Im07y0jhKPctYoktgFS/Eg==)
        password: ENC(Im07y0jhKPctYoktgFS/Eg==)
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      seconddb:
        jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/XE_TEMP?allowMultiQueries=true
        username: ENC(Im07y0jhKPctYoktgFS/Eg==)
        password: ENC(Im07y0jhKPctYoktgFS/Eg==)
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  redis:
      host: localhost
      port: 6379
file:
   upload-dir: c:/temp
server:
  port: 8087
---
spring:
  profiles: devv
  datasource:
        url: jdbc:log4jdbc:mariadb://localhost:3306/XE?allowMultiQueries=true
        username: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        password: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: 2000000
file:
   upload-dir: c:/temp
server:
  port: 8087
---
spring:
  profiles: devkafka
  datasource:
        url: jdbc:log4jdbc:mariadb://localhost:3306/XE?allowMultiQueries=true
        username: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        password: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: 2000000
file:
   upload-dir: c:/temp
server:
  port: 8089
---
spring:
  profiles: erod
  datasource:
        url: jdbc:log4jdbc:mariadb://xe.cwe3sizdhhur.ap-northeast-2.rds.amazonaws.com:3306/XE?allowMultiQueries=true
        username: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        password: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy        
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: 3000000
file:
   upload-dir: c:/temp
server:
  port: 8087     
---    
spring:
  profiles: drod
  datasource:
        url: jdbc:log4jdbc:mariadb://192.168.0.183:3306/XE?allowMultiQueries=true
        username: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        password: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy        
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: 3000000
file:
   upload-dir: c:/temp
server:
  port: 8087     
---
spring:
   profiles: prod
   datasource:
        url: jdbc:mariadb://host.docker.internal:3306/XE?allowMultiQueries=true
        username: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        password: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        driver-class-name: org.mariadb.jdbc.Driver
   redis:
        host: host.docker.internal
        port: 6379
   session:
        store-type: redis
        timeout: 4200
file:
   upload-dir: /data
server:
  port: 8087  
---
spring:
   profiles: prodkafka
   datasource:
        url: jdbc:mariadb://host.docker.internal:3306/XE?allowMultiQueries=true
        username: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        password: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        driver-class-name: org.mariadb.jdbc.Driver
   redis:
        host: host.docker.internal
        port: 6379
   session:
        store-type: redis
        timeout: 4200
file:
   upload-dir: /data
server:
  port: 8089
---
spring:
   profiles: arod
   datasource:
        url: jdbc:mariadb://xe.cwe3sizdhhur.ap-northeast-2.rds.amazonaws.com:3306/XE?allowMultiQueries=true
        username: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        password: ENC(Im07y0jhKPctYoktgFS/Eg==)   
        driver-class-name: org.mariadb.jdbc.Driver
   redis:
        host: 172.31.0.64
        port: 6379
   session:
        store-type: redis
        timeout: 3600
file:
   upload-dir: /data
server:
  port: 8087  

