# yml은 indentation이 정확해야 함.(들어쓰는 칸 수가 같은 레벨에서는 무조건  같아야함.)
# Redis session=================================================================
# Session store type.
#server.servlet.session.timeout= # Session timeout. If a duration suffix is not specified, seconds is used.
#spring.session.redis.flush-mode=on-save # Sessions flush mode.
#spring.session.redis.namespace=spring:session # Namespace for keys used to store sessions.
# Redis server host.
#spring.redis.password= # Login password of the redis server.
# Redis server port. 34.80.117.164  35.229.221.36 

server:
  servlet:
    session:
      timeout: 300m
  session:
    cookie:
      max-age: 3000000
  port: 8087

---    
spring:
  profiles: dev
  datasource:
        url: jdbc:mariadb://localhost:3306/XE?allowMultiQueries=true
        username: EXPS
        password: EXPS
        driver-class-name: org.mariadb.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: 3000000

---
spring:
   profiles: prod
   datasource:
        url: jdbc:mariadb://host.docker.internal:3306/XE?allowMultiQueries=true
        username: EXPS
        password: EXPS
        driver-class-name: org.mariadb.jdbc.Driver
   redis:
        host: host.docker.internal
        port: 30079
        password: 2324
   session:
        store-type: redis
        timeout: 3000000
 


