# Redis session=================================================================
# Session store type.
#server.servlet.session.timeout= # Session timeout. If a duration suffix is not specified, seconds is used.
#spring.session.redis.flush-mode=on-save # Sessions flush mode.
#spring.session.redis.namespace=spring:session # Namespace for keys used to store sessions.
# Redis server host.
#spring.redis.password= # Login password of the redis server.
# Redis server port.
spring:
  redis:
    host: 13.124.131.237
    port: 6380
  session:
    store-type: redis
    timeout: 3000000

server:
  servlet:
    session:
      timeout: 300m
  session:
    cookie:
      max-age: 3000000      

---
spring:
   profiles: dev
   datasource:
    url: jdbc:log4jdbc:oracle:thin:@127.0.0.1:1522:xe

---
spring:
   profiles: prod
   datasource:
    url: jdbc:log4jdbc:oracle:thin:@xe-aws.c5s7gftnkiej.ap-northeast-2.rds.amazonaws.com:1521:xe



